### ISSUE TITLE
QE Certify Release 1.1.1

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#850]
- [x] Verify the critical fixes made for this release. 
     * https://github.com/couchbase/couchbase-lite-ios/commit/9f127a111d0c53baf53e6809d90e6ebc69980e1a
     *  https://github.com/couchbase/couchbase-lite-ios/commit/bc5202b140505d631465a9698191d5746bec9c37
- [x] Verify support added for iOS-9
- [x] Run Integration test suite with Sync Gateway 1.1.1 release
- [x] Verify no existing functionality is broken 
      * Run integration test suite against SG-1.1 and 3.1.0 CB-server build
Note: Separate tickets may be created for adding functional tests.

**Comment by pasin** [comment]
I think we should add a functional test to cover this issue https://github.com/couchbase/couchbase-lite-ios/issues/865 as a part of release certification.

**Comment by ashvindersingh** [comment]
Created issue #902 to add functional test for session cookie not attached on websocket conn #865 . All other other items have been completed for 1.1.1.
